# .github/workflows/cd.yml
name: CD

on:
  push:
    branches:
      - prod
      - release

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/my-react-app:latest
          platforms: linux/amd64,linux/arm64

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.AWS_EC2_HOST }}
          username: ${{ secrets.AWS_EC2_USER }}
          key: ${{ secrets.AWS_SSH_PRIVATE_KEY }}
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/my-react-app:latest
            if [ $(docker ps -q -f name=my-react-app) ]; then
              docker stop my-react-app
            fi
            if [ $(docker ps -a -q -f name=my-react-app) ]; then
              docker rm my-react-app
            fi
            if [ $(lsof -t -i:80) ]; then
              kill -9 $(lsof -t -i:80)
            fi
            docker run -d --name my-react-app -p 80:80 ${{ secrets.DOCKER_USERNAME }}/my-react-app:latest