name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2

      - name: Set up Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Build and run services with Docker Compose
        run: docker-compose up -d --build

      - name: Run Prettier
        run: docker-compose run --rm frontend yarn format
        continue-on-error: true

      - name: Run ESLint
        run: docker-compose run --rm frontend yarn lint
        continue-on-error: true

      - name: Build React App
        run: docker-compose run --rm frontend yarn build

      - name: Run Tests
        run: docker-compose run --rm frontend yarn test --watchAll=false

      - name: Shut down services
        run: docker-compose down
